### ISSUE TITLE
Attribute Error when running main

### ISSUE THREAD

**Issue by CatchACode** [indigocalifornia/mvgen#6]
D:\mvgen-master>python main.py -s vidz --force 1920 1080
CONFIG: {"raw_directory": "/raw", "segments_directory": "/segments", "work_directory": "/work", "ready_directory": "/ready", "audio": "/audio/cardi-b-wap-feat-megan-thee-stallion-official-music-video.mp3", "duration": 4, "bpm": "auto", "delete_work_dir": 1, "offset": 0, "force": ["1920", "1080"], "segment_duration": 2, "segment_start": 10, "segment_end": 10, "force_segment": false, "sources": ["vidz"]}
AUDIO: Processing /audio/cardi-b-wap-feat-megan-thee-stallion-official-music-video.wav
AUDIO: Detecting BPM
Traceback (most recent call last):
  File "D:\mvgen-master\main.py", line 143, in <module>
    run(args)
  File "D:\mvgen-master\main.py", line 128, in run
    final_file = MVGen.run(config)
  File "D:\mvgen-master\mvgen\mvgen.py", line 450, in run
    gen.load_audio(**get_args(config, MVGen.load_audio))
  File "D:\mvgen-master\mvgen\mvgen.py", line 157, in load_audio
    self.beats = self._process_audio(self.audio, bpm)
  File "D:\mvgen-master\mvgen\mvgen.py", line 215, in _process_audio
    if audio.suffix != '.wav':
AttributeError: 'str' object has no attribute 'suffix'

**Comment by CatchACode** [comment]
paths were wrongly configured
